apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ceph-csi-rbd-storageclass
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/richpea1982/k3s
    targetRevision: HEAD
    path: gitops/manifests/ceph-csi-rbd
  destination:
    server: https://kubernetes.default.svc
    namespace: ceph-csi-rbd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
