apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crowdsec
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://crowdsecurity.github.io/helm-charts
    chart: crowdsec
    targetRevision: "0.24.0"
    helm:
      values: |
        agent:
          env:
            - name: COLLECTIONS
              value: "crowdsecurity/traefik crowdsecurity/linux"
            - name: PARSERS
              value: "crowdsecurity/cri-logs"
          acquisition: []
          additionalAcquisitions:
            - filenames:
                - /var/log/containers/traefik-*_kube-system_traefik-*.log
              type: cri-logs
              labels:
                type: traefik
              poll_without_inotify: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
