apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crowdsec
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://crowdsecurity.github.io/helm-charts
    chart: crowdsec
    targetRevision: "0.24.0"
    helm:
      values: |
        agent:
          acquisition:
            - namespace: kube-system
              podName: traefik-*
              program: traefik
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
