apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: crowdsec-bouncer
  namespace: kube-system
spec:
  plugin:
    crowdsec-bouncer:
      enabled: true
      crowdsecLapiScheme: "http"
      crowdsecLapiHost: "crowdsec-service.kube-system.svc.cluster.local:8080"
      secretName: "crowdsec-traefik-bouncer-key"
      crowdsecLapiKeySecretVariable: "crowdsec-lapi-key"
      crowdsecMode: "stream"
